/**
 * Parity with the design handoff: `__fixtures__/design-geometry.json` was generated by running the
 * design's own drawing engine (sugo-drawings.js, 2026-09-25) for every part, machine and the map at
 * three scales. The port must reproduce it exactly, path for path and in the same order (the order
 * drives the plotter animation).
 */
import fixtures from '../__fixtures__/design-geometry.json';
import type { Drawing } from './layer';
import { PART_GEOMETRY, type PartKind } from './parts-table';
import { drawTurned } from './turned';

type DesignText = { x: number; y: number; s: number; str: string; a?: string; acc?: number; grey?: number };
type DesignLayer = {
  k: number;
  cls: string;
  thick: string[];
  thin: string[];
  cl: string[];
  hatch: string[];
  env: string[];
  envThin: string[];
  envFill: string[];
  txt: DesignText[];
  fill: string[];
  road?: string[];
};
type DesignDrawing = { bs: DesignLayer[]; vb: number[]; region?: number[]; oy?: number };
type PartFixture = {
  type: string;
  front: Record<string, DesignDrawing>;
  full: Record<string, DesignDrawing>;
  noCut?: DesignDrawing;
};

const partFixtures = fixtures.parts as Record<string, PartFixture>;

function toDesignShape(drawing: Drawing): DesignDrawing {
  return {
    bs: drawing.layers.map((layer) => ({
      k: layer.k,
      cls: layer.view ? `v${layer.view}` : '',
      thick: layer.thick,
      thin: layer.thin,
      cl: layer.centre,
      hatch: layer.hatch,
      env: layer.envelope,
      envThin: layer.envelopeThin,
      envFill: layer.envelopeFill,
      txt: layer.texts.map((t) => ({
        x: t.x,
        y: t.y,
        s: t.size,
        str: t.text,
        a: t.anchor,
        ...(t.accent && { acc: 1 }),
        ...(t.muted && { grey: 1 }),
      })),
      fill: layer.fills,
      ...(layer.roads.length > 0 && { road: layer.roads }),
    })),
    vb: [...drawing.viewBox],
    ...(drawing.region && { region: [...drawing.region] }),
    ...(drawing.planOffset !== undefined && { oy: drawing.planOffset }),
  };
}

const kinds = (type: 'turned' | 'milled') =>
  (Object.keys(PART_GEOMETRY) as PartKind[]).filter((kind) => PART_GEOMETRY[kind].type === type);

describe.each(kinds('turned'))('turned part %s', (kind) => {
  it.each(['front', 'full'] as const)('matches the design engine in the %s view at every scale', (views) => {
    const part = PART_GEOMETRY[kind];
    if (part.type !== 'turned') throw new Error(`${kind} is not turned`);
    for (const k of fixtures.k) {
      expect(toDesignShape(drawTurned(part, k, views))).toEqual(partFixtures[kind][views][String(k)]);
    }
  });
});

it('covers every part the design engine was sampled for', () => {
  expect(Object.keys(PART_GEOMETRY).sort()).toEqual(Object.keys(partFixtures).sort());
});
