import React from 'react';
import Head from "next/head";
import {ProductsGallery} from "@/components";
import Headline from "@/components/Headline/Headline";

const Products = () => {
    return (
        <>
            <Head>
                <title>Izdelki</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Headline  description={'Naši izdelki'} title={'Izdelki'}/>
            <ProductsGallery />
        </>
    );
};

export default Products;