import React from 'react';
import Head from 'next/head';
import { MachineParkGallery } from '@/components';
import Headline from "@/components/Headline/Headline";



const MachineParkPage = () => {
    return (
        <>
            <Head>
                <title>Strojni park</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Headline  description={'Sodobno opremljen strojni park za reševanje tudi najbolj zahtevnih problemov'} title={'Strojni park'}/>
            <MachineParkGallery />
        </>
    );
};

export default MachineParkPage;